-- One row per materialization attempt.
--
-- The correlation id is the thread that ties a run's log lines, job statuses and diagnostics
-- together; it is generated by the application before the run starts so it can be logged even if
-- this insert fails.
CREATE TABLE ingestion.runs (
    id                  UUID         NOT NULL,
    correlation_id      VARCHAR(64)  NOT NULL,
    repository_id       UUID,
    trigger_type        VARCHAR(32)  NOT NULL,
    state               VARCHAR(32)  NOT NULL,
    requested_revision  VARCHAR(200),
    documents_total     INTEGER      NOT NULL DEFAULT 0,
    documents_succeeded INTEGER      NOT NULL DEFAULT 0,
    documents_failed    INTEGER      NOT NULL DEFAULT 0,
    documents_skipped   INTEGER      NOT NULL DEFAULT 0,
    started_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    finished_at         TIMESTAMPTZ,

    CONSTRAINT pk_runs PRIMARY KEY (id),
    CONSTRAINT uq_runs_correlation UNIQUE (correlation_id),
    CONSTRAINT fk_runs_repository
        FOREIGN KEY (repository_id) REFERENCES source.repositories (id) ON DELETE SET NULL,
    CONSTRAINT ck_runs_trigger_type CHECK (trigger_type IN ('WEBHOOK', 'MANUAL', 'SCHEDULED')),
    CONSTRAINT ck_runs_state
        CHECK (state IN ('RUNNING', 'SUCCEEDED', 'PARTIALLY_SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_runs_finished CHECK (state = 'RUNNING' OR finished_at IS NOT NULL)
);

CREATE INDEX idx_runs_repository_started ON ingestion.runs (repository_id, started_at DESC);
